# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b867567c88c46c778808dc66a60e95f1ffc6c93c3d07cc87b1b227cec5ac58bda31473babe2a116b82b973de4bdbb453ba520895aae359dc7c46eba49979cf5

test:
  secret_key_base: ea171aa968049f47a00b594bc685f9a1113db13a1992e145466ca884157b2f8ebac4b1f945ead65a3fac472d236c13cd63c729a550753080db0d6028d1610aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
